__Q1: Questions on Basic NumPy Array<br>
(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])<br>
(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any two 
NumPy in-built methods<br>
(c) Compare the following numpy arrays:<br>
arr1 = np.array([[1, 2], [3, 4]])<br>
arr2 = np.array([[1, 2], [3, 4]])__

In [3]:
import numpy as np 
arr = np.array([1,2,3,4,5])
reversed_arr = np.flip(arr)
print(" a. reversed array:", reversed_arr)

array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flattened_arr1 = array1.flatten()
print(" b. flattened array:", flattened_arr1)

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
print(" c. equality:",np.array_equal(arr1, arr2))

 a. reversed array: [5 4 3 2 1]
 b. flattened array: [1 2 3 2 4 5 1 2 3]
 c. equality: True


__(d) Find the most frequent value and their indice(s) in the following arrays:<br> 
i. x = np.array([1,2,3,4,5,1,2,1,1,1]) <br>
ii.y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])<br>__

In [5]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

# Most frequent value in x
most_freq_value_x = np.bincount(x).argmax()
#bincount creates a frequency array for the elements in x
#argmax finds the index with max value
indices_x = np.where(x == most_freq_value_x)

# Most frequent value in y
most_freq_value_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_value_y)

print("i. most frequent value is",most_freq_value_x,"indices are",indices_x[0])
print("i. most frequent value is",most_freq_value_y,"indices are",indices_y[0])


i. most frequent value is 1 indices are [0 5 7 8 9]
i. most frequent value is 1 indices are [0 1 2]


__(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find <br>
   i.Sum of all elements <br>
   ii.Sum of all elements row-wise <br>
   iii.Sum of all elements column-wise<br>__


In [6]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("i.", gfg.sum())
print()
print("ii.", gfg.sum(axis = 1))
print()
print("iii.", gfg.sum(axis=0))

i. 45

ii. [[14]
 [16]
 [15]]

iii. [[20  9 16]]


__(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find <br>
i. Sum of diagonal elements <br>
ii. Eigen values of matrix <br>
iii.Eigen vectors of matrix <br>
iv. Inverse of matrix <br>
v. Determinant of matrix <br>__

 
 


In [7]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
# Sum of diagonal elements
print("i.",np.trace(n_array))
print()
# Eigenvalues
eigen_values, eigen_vectors = np.linalg.eig(n_array)
print("ii.",eigen_values)
print()
print("iii.",eigen_vectors)
print()
# Determinant of matrix
print("iv.",np.linalg.det(n_array))
print()
# Inverse of matrix
print("v.",np.linalg.inv(n_array))

i. 176

ii. [98.16835147 28.097044   49.73460452]

iii. [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]

iv. 137180.0000000001

v. [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]


__(g) Multiply the following matrices and also find covariance between matrices using NumPy: <br>
i. p = [[1, 2], [2, 3]] <br>
 q = [[4, 5], [6, 7]] <br>
ii. 
p = [[1, 2], [2, 3], [4, 5]] <br>
q = [[4, 5, 1], [6, 7, 2]] <br>__

In [8]:

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
product =np.dot(p, q)
print("i. Multiplication: ",product)
print(" Covariance: ", np.cov(product))
print()

p = np.array([[1, 2], [2, 3], [4, 5]])
q = np.array([[4, 5, 1], [6, 7, 2]])
product =np.dot(p, q)
print("ii. Multiplication: ",product)
print(" Covariance: ", np.cov(product))



i. Multiplication:  [[16 19]
 [26 31]]
 Covariance:  [[ 4.5  7.5]
 [ 7.5 12.5]]

ii. Multiplication:  [[16 19  5]
 [26 31  8]
 [46 55 14]]
 Covariance:  [[ 54.33333333  89.16666667 158.83333333]
 [ 89.16666667 146.33333333 260.66666667]
 [158.83333333 260.66666667 464.33333333]]


__(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]), 
find inner, outer and cartesian product?__

In [9]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
inner_product = np.inner(x, y)

outer_product = np.outer(x, y)

import itertools
cartesian_product = np.array(list(itertools.product(x, y)))
inner_product, outer_product, cartesian_product

(array([[17, 52],
        [13, 62]]),
 array([[ 2, 10,  0, 10, 20,  6],
        [ 3, 15,  0, 15, 30,  9],
        [ 4, 20,  0, 20, 40, 12],
        [ 3, 15,  0, 15, 30,  9],
        [ 2, 10,  0, 10, 20,  6],
        [ 9, 45,  0, 45, 90, 27]]),
 array([[[ 2,  3,  4],
         [ 1,  5,  0]],
 
        [[ 2,  3,  4],
         [ 5, 10,  3]],
 
        [[ 3,  2,  9],
         [ 1,  5,  0]],
 
        [[ 3,  2,  9],
         [ 5, 10,  3]]]))

__Q2: Based on NumPy Mathematics and Statistics <br>
(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])<br>
i.Find element-wise absolute value<br>
ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each 
row.<br>
iii.Mean, Median and Standard Deviation of flattened array, of each column, and 
each row <br>__
 

In [17]:
a = np.array([[1, -2, 3], [-4, 5, -6]])

#i. Element-wise absolute value
abs_a = np.abs(a)
print("i.", abs_a)

#ii. 25th, 50th, and 75th percentiles
percentiles = np.percentile(a.flatten(), [25, 50, 75])
print("ii. 25th :",percentiles[0])
print("50th :",percentiles[1])
print("75th :",percentiles[2])
#iii. Mean, median, standard deviation
mean = np.mean(a.flatten())
median = np.median(a.flatten())
std_dev = np.std(a.flatten())
print("iii. Mean:", mean,"Median:",median,"Standard Deviation:",std_dev)

i. [[1 2 3]
 [4 5 6]]
ii. 25th : -3.5
50th : -0.5
75th : 2.5
iii. Mean: -0.5 Median: -0.5 Standard Deviation: 3.8622100754188224


__(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling 
and truncated value, rounded values__

In [18]:
a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])
# Floor values
floor_values = np.floor(a)

# Ceiling values
ceiling_values = np.ceil(a)

# Truncated values
truncated_values = np.trunc(a)

floor_values, ceiling_values, truncated_values

(array([-2., -2., -1.,  0.,  1.,  1.,  3.]),
 array([-1., -1., -0.,  1.,  2.,  2.,  3.]),
 array([-1., -1., -0.,  0.,  1.,  1.,  3.]))

__Q3: Based on Searching and Sorting<br>
(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find <br>
i. Sorted array<br>
ii.Indices of sorted array <br>
iii. 4 smallest elements <br>
iv.5 largest elements<br>__
 


 

In [24]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
print("i.",sorted_array)
print("ii.",np.argsort(array))
print("iii.",sorted_array[:4])
print("iv.",sorted_array[-5:])

i. [ 10  16  16  52  54  62 453]
ii. [0 3 4 1 5 2 6]
iii. [10 16 16 52]
iv. [ 16  52  54  62 453]


__(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find<br>
i. Integer elements only<br>
ii. Float elements only__

In [33]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

int_elements = array[array == array.astype(int)]
print("i. Integer elements:", int_elements)


float_elements = array[array != array.astype(int)]
print("ii. Float elements:", float_elements)


i. Integer elements: [1. 2. 3. 2.]
ii. Float elements: [1.2 2.2]


__Q4: (a) Write a function named img_to_array(path) that reads an image from a specified path and 
save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale 
images)<br>
(b) Load the saved file into jupyter notebook?<br>__

In [10]:
from PIL import Image
import numpy as np
def img_to_array(path):
    img = Image.open(path)
    img_array = np.array(img)
    
    if len(img_array.shape) == 3:  # RGB image
        np.savetxt('image_rgb.txt', img_array.reshape(-1, img_array.shape[2]), fmt='%d')
    else:  # Grayscale image
        np.savetxt('image_gray.txt', img_array, fmt='%d')
    
    return img_array

img_to_array(r'C:\Users\Hp\OneDrive\Desktop\resized.jpg')


img_array_rgb = np.loadtxt('image_rgb.txt')


print(img_array_rgb)


[[255. 255. 255.]
 [255. 255. 255.]
 [255. 255. 255.]
 ...
 [165. 108.  63.]
 [168. 111.  66.]
 [172. 115.  70.]]
